#!/usr/bin/env bash
# Indefinitely writes "I am alive" to the file /tmp/my_process.
# put a pause for two seconds in between each message.

while true

do

  echo "I am alive!" >> /tmp/my_process

  sleep 2

done
